// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

// Let us list the factors of the first seven triangle numbers:

//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.

// What is the value of the first triangle number to have over five hundred divisors?

function f(x){
  var n = 0;
  var as = [];
  for(i=1;i<=x;i++){
    n = n + i;
    as.push(n);
  }
  return as;
}

function g(as){
  for(var i in as){
    var y = 1;
    var sqrt = Math.sqrt(as[i]);
    for(var j=1;j<=sqrt;j++){
      if(as[i]%j==0){      
        y = y + 1;
      }
    }
    if(as[i]%sqrt===0){
      y = (y - 1) * 2 + 1;
    } else {
      y = y * 2;
    }
    if(y>500)
      break;
  }
  return as[i];
}



var a = g(f(100000));
console.log(a);


